### ISSUE TITLE
Watch mode not reloading

### ISSUE THREAD

**Issue by picheli20** [ui-jar/ui-jar#47]
I'm trying to implement this project in my development flow, but without the watch mode will be almost impossible to check the component changes.

I've created an example based on https://github.com/ui-jar/ui-jar/issues/34, you can check the repo  https://github.com/picheli20/ui-jar/commit/b7b38bc12e39b3c5cd31d8684a2ec9bc64f39504
```
    "ui-jar": "node node_modules/ui-jar/dist/bin/cli.js --directory ./src/app/ --includes \\.ts$",
    "docs:watch": "npm run ui-jar -- --watch",
    "start-ui-jar-example": "concurrently \"npm run docs:watch\" \"ng serve ui-jar\""
```

Basically just adding `--watch` doesn't trigger the live-reload at all, if you edit any component description will not change.

**Comment by picheli20** [comment]
After some investigation, looks like the watcher is not being called (https://github.com/ui-jar/ui-jar/blob/master/src/watcher/watcher.ts#L26), my OS is Ubuntu

**Comment by picheli20** [comment]
Just just one question out of curiosity, the watch mode doesn't re-build the component it-self? Just the description/examples for it?

**Comment by nording** [comment]
> Just just one question out of curiosity, the watch mode just rebuild the testing component (what I could see), is there a way to reload for any changes related to what component?

The reason that the watcher only listening on changes in test files is because of performance. If the watcher listening on all files changes it will have to rebuild every time a change is triggered - and a rebuild build take some time. 
The downside with the watcher not listening on all file changes is that your @description, @component and @group annotation won't update without a rebuild. I recommend to do a full rebuild on that kind of changes.

UI-jar only import your components files, hence it doesn't need to rebuild every time a change is triggered in your component files (as your ordinary build system will trigger on that changes and rebuild the component file that UI-jar imports).

**Comment by picheli20** [comment]
@nording I understand, maybe we can create some kinda of options, if the change is in the component it-self (logic, template, notations) we can do a build for everything?

Will play around with the code and see if there's some reasonably solution :)

**Comment by picheli20** [comment]
I'll close it since it main issue was solved :) Just the live-reloading of the entire project is something that would help a lot, but what I understood now would be a bit hard to implement it for now

**Comment by nording** [comment]
Allright! I have just published v1.1.7 on npm!

**Comment by Maks-Yaremenko** [comment]
I can't get how to run watcher?... And why ui-jar won't rebuild everything on changes in my components from the common app.

**Comment by picheli20** [comment]
@Maks-Yaremenko is what @nording said here: https://github.com/ui-jar/ui-jar/issues/47#issuecomment-435166690

At the moment is just reloading the tests, not the components, I've done as a temporary solution is comment out the rebuild filter, so you can re-load the components, till figure out a better solution :) You can check this commit: https://github.com/picheli20/ui-jar/commit/d4d83ba800e7939af0aef32e129b1fc3d721983a#diff-44c164274b5283acdd8c52f95daee66fL49
